# Generated by Django 2.0 on 2018-01-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoPrivado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_minatura', models.ImageField(upload_to='img_proyectos/')),
                ('imagenes', models.FileField(blank=True, null=True, upload_to='img_proyectos/')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoPublico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_minatura', models.ImageField(upload_to='img_proyectos/')),
                ('imagenes', models.FileField(blank=True, null=True, upload_to='img_proyectos/')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
        ),
    ]
