# Generated by Django 2.0.5 on 2018-05-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoPrivado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('img_minatura', models.ImageField(upload_to='img_proyectos/', verbose_name='Imagen principal')),
                ('img_principal', models.ImageField(blank=True, null=True, upload_to='img_proyectos/', verbose_name='Imagen banner')),
                ('img1', models.FileField(blank=True, null=True, upload_to='img_proyectos/')),
                ('img2', models.FileField(blank=True, null=True, upload_to='img_proyectos/')),
                ('img3', models.FileField(blank=True, null=True, upload_to='img_proyectos/')),
                ('img4', models.FileField(blank=True, null=True, upload_to='img_proyectos/')),
                ('img5', models.FileField(blank=True, null=True, upload_to='img_proyectos/')),
                ('img6', models.FileField(blank=True, null=True, upload_to='img_proyectos/')),
                ('resaltar', models.BooleanField(default=False)),
                ('plus_mensaje', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_propiedad', models.CharField(blank=True, max_length=20, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Area')),
                ('ubicacion', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_negocio', models.CharField(blank=True, max_length=20, null=True)),
                ('parqueadero', models.BooleanField(default=False)),
                ('parqueadero_visitantes', models.BooleanField(default=False)),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('zonas_verdes', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoPublico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('img_minatura', models.ImageField(upload_to='img_proyectos/', verbose_name='Imagen principal')),
                ('img_principal', models.ImageField(blank=True, null=True, upload_to='img_proyectos/', verbose_name='Imagen banner')),
                ('img1', models.FileField(blank=True, null=True, upload_to='img_proyectos/')),
                ('img2', models.FileField(blank=True, null=True, upload_to='img_proyectos/')),
                ('img3', models.FileField(blank=True, null=True, upload_to='img_proyectos/')),
                ('img4', models.FileField(blank=True, null=True, upload_to='img_proyectos/')),
                ('img5', models.FileField(blank=True, null=True, upload_to='img_proyectos/')),
                ('img6', models.FileField(blank=True, null=True, upload_to='img_proyectos/')),
                ('img7', models.FileField(blank=True, null=True, upload_to='img_proyectos/')),
            ],
        ),
    ]
