# Generated by Django 2.0 on 2018-01-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_auto_20180127_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectoprivado',
            name='img_principal',
            field=models.ImageField(blank=True, null=True, upload_to='img_proyectos/'),
        ),
        migrations.AddField(
            model_name='proyectoprivado',
            name='mostrar_al_inicio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proyectopublico',
            name='img_principal',
            field=models.ImageField(blank=True, null=True, upload_to='img_proyectos/'),
        ),
        migrations.AddField(
            model_name='proyectopublico',
            name='mostrar_al_inicio',
            field=models.BooleanField(default=False),
        ),
    ]
