# Generated by Django 2.0 on 2018-04-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_auto_20180128_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectoprivado',
            name='img10',
        ),
        migrations.RemoveField(
            model_name='proyectoprivado',
            name='img7',
        ),
        migrations.RemoveField(
            model_name='proyectoprivado',
            name='img8',
        ),
        migrations.RemoveField(
            model_name='proyectoprivado',
            name='img9',
        ),
        migrations.RemoveField(
            model_name='proyectoprivado',
            name='mostrar_al_inicio',
        ),
        migrations.RemoveField(
            model_name='proyectopublico',
            name='img10',
        ),
        migrations.RemoveField(
            model_name='proyectopublico',
            name='img8',
        ),
        migrations.RemoveField(
            model_name='proyectopublico',
            name='img9',
        ),
        migrations.RemoveField(
            model_name='proyectopublico',
            name='mostrar_al_inicio',
        ),
        migrations.AlterField(
            model_name='proyectoprivado',
            name='img_minatura',
            field=models.ImageField(upload_to='img_proyectos/', verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='proyectoprivado',
            name='img_principal',
            field=models.ImageField(blank=True, null=True, upload_to='img_proyectos/', verbose_name='Imagen banner'),
        ),
        migrations.AlterField(
            model_name='proyectopublico',
            name='img_minatura',
            field=models.ImageField(upload_to='img_proyectos/', verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='proyectopublico',
            name='img_principal',
            field=models.ImageField(blank=True, null=True, upload_to='img_proyectos/', verbose_name='Imagen banner'),
        ),
    ]
