# Generated by Django 2.0 on 2018-01-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImgInicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='pic_folder/')),
                ('img2', models.ImageField(upload_to='pic_folder/')),
            ],
        ),
    ]
