# Generated by Django 2.0 on 2018-01-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('correo', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('mensaje', models.CharField(max_length=1000, verbose_name='Mensaje')),
            ],
        ),
    ]
