# Generated by Django 2.0.5 on 2018-05-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180414_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioninicio',
            name='imgbanner1',
            field=models.CharField(max_length=1000, verbose_name='Imagen de Banner 1'),
        ),
        migrations.AlterField(
            model_name='configuracioninicio',
            name='imgbanner2',
            field=models.CharField(max_length=1000, verbose_name='Imagen de Banner 2'),
        ),
        migrations.AlterField(
            model_name='configuracioninicio',
            name='imgbanner3',
            field=models.CharField(max_length=1000, verbose_name='Imagen de Banner 3'),
        ),
        migrations.AlterField(
            model_name='configuracioninicio',
            name='proyectoventa1',
            field=models.CharField(max_length=1000, verbose_name='Proyecto en venta 1'),
        ),
        migrations.AlterField(
            model_name='configuracioninicio',
            name='proyectoventa2',
            field=models.CharField(max_length=1000, verbose_name='Proyecto en venta 2'),
        ),
        migrations.AlterField(
            model_name='configuracioninicio',
            name='proyectoventa3',
            field=models.CharField(max_length=1000, verbose_name='Proyecto en venta 3'),
        ),
    ]
