# Generated by Django 2.0.5 on 2018-07-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20180508_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioninicio',
            name='imgbanner1',
            field=models.CharField(choices=[('1 ProyectoPublico', 'ProyectoPublico: Proyecto1'), ('2 ProyectoPublico', 'ProyectoPublico: Proyecto2'), ('3 ProyectoPublico', 'ProyectoPublico: Proyecto3'), ('4 ProyectoPublico', 'ProyectoPublico: Proyecto4'), ('5 ProyectoPublico', 'ProyectoPublico: Proyecto5'), ('6 ProyectoPublico', 'ProyectoPublico: Proyecto6'), ('1 ProyectoPrivado', 'ProyectoPrivado: Proyecto1'), ('2 ProyectoPrivado', 'ProyectoPrivado: Proyecto2'), ('3 ProyectoPrivado', 'ProyectoPrivado: Proyecto3'), ('4 ProyectoPrivado', 'ProyectoPrivado: Proyecto4'), ('5 ProyectoPrivado', 'ProyectoPrivado: Proyecto5'), ('6 ProyectoPrivado', 'ProyectoPrivado: Proyecto6'), ('7 ProyectoPrivado', 'ProyectoPrivado: Proyecto7')], max_length=1000, verbose_name='Imagen de Banner 1'),
        ),
        migrations.AlterField(
            model_name='configuracioninicio',
            name='imgbanner2',
            field=models.CharField(choices=[('1 ProyectoPublico', 'ProyectoPublico: Proyecto1'), ('2 ProyectoPublico', 'ProyectoPublico: Proyecto2'), ('3 ProyectoPublico', 'ProyectoPublico: Proyecto3'), ('4 ProyectoPublico', 'ProyectoPublico: Proyecto4'), ('5 ProyectoPublico', 'ProyectoPublico: Proyecto5'), ('6 ProyectoPublico', 'ProyectoPublico: Proyecto6'), ('1 ProyectoPrivado', 'ProyectoPrivado: Proyecto1'), ('2 ProyectoPrivado', 'ProyectoPrivado: Proyecto2'), ('3 ProyectoPrivado', 'ProyectoPrivado: Proyecto3'), ('4 ProyectoPrivado', 'ProyectoPrivado: Proyecto4'), ('5 ProyectoPrivado', 'ProyectoPrivado: Proyecto5'), ('6 ProyectoPrivado', 'ProyectoPrivado: Proyecto6'), ('7 ProyectoPrivado', 'ProyectoPrivado: Proyecto7')], max_length=1000, verbose_name='Imagen de Banner 2'),
        ),
        migrations.AlterField(
            model_name='configuracioninicio',
            name='imgbanner3',
            field=models.CharField(choices=[('1 ProyectoPublico', 'ProyectoPublico: Proyecto1'), ('2 ProyectoPublico', 'ProyectoPublico: Proyecto2'), ('3 ProyectoPublico', 'ProyectoPublico: Proyecto3'), ('4 ProyectoPublico', 'ProyectoPublico: Proyecto4'), ('5 ProyectoPublico', 'ProyectoPublico: Proyecto5'), ('6 ProyectoPublico', 'ProyectoPublico: Proyecto6'), ('1 ProyectoPrivado', 'ProyectoPrivado: Proyecto1'), ('2 ProyectoPrivado', 'ProyectoPrivado: Proyecto2'), ('3 ProyectoPrivado', 'ProyectoPrivado: Proyecto3'), ('4 ProyectoPrivado', 'ProyectoPrivado: Proyecto4'), ('5 ProyectoPrivado', 'ProyectoPrivado: Proyecto5'), ('6 ProyectoPrivado', 'ProyectoPrivado: Proyecto6'), ('7 ProyectoPrivado', 'ProyectoPrivado: Proyecto7')], max_length=1000, verbose_name='Imagen de Banner 3'),
        ),
        migrations.AlterField(
            model_name='configuracioninicio',
            name='proyectoventa1',
            field=models.CharField(choices=[('1 ProyectoPublico', 'ProyectoPublico: Proyecto1'), ('2 ProyectoPublico', 'ProyectoPublico: Proyecto2'), ('3 ProyectoPublico', 'ProyectoPublico: Proyecto3'), ('4 ProyectoPublico', 'ProyectoPublico: Proyecto4'), ('5 ProyectoPublico', 'ProyectoPublico: Proyecto5'), ('6 ProyectoPublico', 'ProyectoPublico: Proyecto6'), ('1 ProyectoPrivado', 'ProyectoPrivado: Proyecto1'), ('2 ProyectoPrivado', 'ProyectoPrivado: Proyecto2'), ('3 ProyectoPrivado', 'ProyectoPrivado: Proyecto3'), ('4 ProyectoPrivado', 'ProyectoPrivado: Proyecto4'), ('5 ProyectoPrivado', 'ProyectoPrivado: Proyecto5'), ('6 ProyectoPrivado', 'ProyectoPrivado: Proyecto6'), ('7 ProyectoPrivado', 'ProyectoPrivado: Proyecto7')], max_length=1000, verbose_name='Proyecto en venta 1'),
        ),
        migrations.AlterField(
            model_name='configuracioninicio',
            name='proyectoventa2',
            field=models.CharField(choices=[('1 ProyectoPublico', 'ProyectoPublico: Proyecto1'), ('2 ProyectoPublico', 'ProyectoPublico: Proyecto2'), ('3 ProyectoPublico', 'ProyectoPublico: Proyecto3'), ('4 ProyectoPublico', 'ProyectoPublico: Proyecto4'), ('5 ProyectoPublico', 'ProyectoPublico: Proyecto5'), ('6 ProyectoPublico', 'ProyectoPublico: Proyecto6'), ('1 ProyectoPrivado', 'ProyectoPrivado: Proyecto1'), ('2 ProyectoPrivado', 'ProyectoPrivado: Proyecto2'), ('3 ProyectoPrivado', 'ProyectoPrivado: Proyecto3'), ('4 ProyectoPrivado', 'ProyectoPrivado: Proyecto4'), ('5 ProyectoPrivado', 'ProyectoPrivado: Proyecto5'), ('6 ProyectoPrivado', 'ProyectoPrivado: Proyecto6'), ('7 ProyectoPrivado', 'ProyectoPrivado: Proyecto7')], max_length=1000, verbose_name='Proyecto en venta 2'),
        ),
        migrations.AlterField(
            model_name='configuracioninicio',
            name='proyectoventa3',
            field=models.CharField(choices=[('1 ProyectoPublico', 'ProyectoPublico: Proyecto1'), ('2 ProyectoPublico', 'ProyectoPublico: Proyecto2'), ('3 ProyectoPublico', 'ProyectoPublico: Proyecto3'), ('4 ProyectoPublico', 'ProyectoPublico: Proyecto4'), ('5 ProyectoPublico', 'ProyectoPublico: Proyecto5'), ('6 ProyectoPublico', 'ProyectoPublico: Proyecto6'), ('1 ProyectoPrivado', 'ProyectoPrivado: Proyecto1'), ('2 ProyectoPrivado', 'ProyectoPrivado: Proyecto2'), ('3 ProyectoPrivado', 'ProyectoPrivado: Proyecto3'), ('4 ProyectoPrivado', 'ProyectoPrivado: Proyecto4'), ('5 ProyectoPrivado', 'ProyectoPrivado: Proyecto5'), ('6 ProyectoPrivado', 'ProyectoPrivado: Proyecto6'), ('7 ProyectoPrivado', 'ProyectoPrivado: Proyecto7')], max_length=1000, verbose_name='Proyecto en venta 3'),
        ),
    ]
