# Generated by Django 2.0 on 2018-01-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5, verbose_name='Número')),
                ('year', models.DateField(unique_for_year=True, verbose_name='Año')),
                ('numero_en_proponente', models.IntegerField(verbose_name='Número en proponente')),
                ('objeto', models.CharField(max_length=1000, verbose_name='Objeto')),
                ('tipo_de_obra', models.CharField(choices=[('tipo1', 'CONSTRUCCIÓN DE EDIFICACIONES'), ('tipo2', 'MANTENIMIENTO Y REMODELACIÓN DE EDIFICACIONES'), ('tipo3', 'INFRAESTRUCTURA VIAL'), ('tipo4', 'OBRAS DE URBANISMO O ESPACIO PUBLICO'), ('tipo5', 'ADECUACION Y MOVIMIENTO DE TIERRAS'), ('tipo6', 'CONSULTORIA Y DISEÑO'), ('tipo7', 'INTERVENTORIA EN INFRAESTRUCTURA VIAL'), ('tipo8', 'CONSTRUCCIÓN DE ALCANTARILLADOS Y ACUEDUCTOS'), ('tipo9', 'INFRAESTRUCTURA ELÉCTRICA')], max_length=1000, verbose_name='Tipo de obra')),
                ('entidad_contratante', models.CharField(max_length=200, verbose_name='Entidad contratante')),
                ('valor_ejecutado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor ejecutado')),
                ('plazo_en_dias', models.IntegerField(verbose_name='Plazo en días')),
                ('fecha_terminacion', models.DateField(verbose_name='Fecha de terminación')),
                ('valor_en_sm', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor en salarios mínimos')),
                ('porcentaje_participacion', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Porcentaje de participación')),
                ('valor_en_sm_participacion', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor en SM segun participación')),
                ('departamento', models.CharField(max_length=200, verbose_name='Departamento')),
                ('municipio', models.CharField(max_length=200, verbose_name='Municipio')),
            ],
        ),
    ]
