# Generated by Django 2.0 on 2018-01-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='year',
            field=models.DateField(unique_for_year='pub_date', verbose_name='Año'),
        ),
    ]
