# Generated by Django 2.0 on 2018-01-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_auto_20180101_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='year',
            field=models.IntegerField(verbose_name='Año'),
        ),
    ]
