# Generated by Django 2.0 on 2018-01-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_auto_20180101_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorSM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor salario mínimo')),
            ],
        ),
    ]
