# Generated by Django 2.0 on 2018-01-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_valorsm'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='acta_liquidacion',
            field=models.FileField(blank=True, null=True, upload_to='my_folder'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='acta_recibo_final',
            field=models.FileField(blank=True, null=True, upload_to='my_folder'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='acuerdo_consorcial',
            field=models.FileField(blank=True, null=True, upload_to='my_folder'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='adicional1',
            field=models.FileField(blank=True, null=True, upload_to='my_folder'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='adicional2',
            field=models.FileField(blank=True, null=True, upload_to='my_folder'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='certificacion_de_obra',
            field=models.FileField(blank=True, null=True, upload_to='my_folder'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='certificacion_director',
            field=models.FileField(blank=True, null=True, upload_to='my_folder'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='contrato',
            field=models.FileField(blank=True, null=True, upload_to='my_folder'),
        ),
    ]
