# Generated by Django 2.0 on 2018-04-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_auto_20180105_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='valor_en_sm',
        ),
    ]
