# Generated by Django 2.0.5 on 2018-07-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_auto_20180414_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='porcentaje_participacion',
            field=models.DecimalField(decimal_places=5, max_digits=6, verbose_name='Porcentaje de participación'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo_de_obra',
            field=models.CharField(choices=[('CONSTRUCCIÓN DE EDIFICACIONES', 'CONSTRUCCIÓN DE EDIFICACIONES'), ('MANTENIMIENTO Y REMODELACIÓN DE EDIFICACIONES', 'MANTENIMIENTO Y REMODELACIÓN DE EDIFICACIONES'), ('INFRAESTRUCTURA VIAL', 'INFRAESTRUCTURA VIAL'), ('OBRAS DE URBANISMO O ESPACIO PUBLICO', 'OBRAS DE URBANISMO O ESPACIO PUBLICO'), ('ADECUACION Y MOVIMIENTO DE TIERRAS', 'ADECUACION Y MOVIMIENTO DE TIERRAS'), ('CONSULTORIA Y DISEÑO', 'CONSULTORIA Y DISEÑO'), ('INTERVENTORIA EN INFRAESTRUCTURA VIAL', 'INTERVENTORIA EN INFRAESTRUCTURA VIAL'), ('CONSTRUCCIÓN DE ALCANTARILLADOS Y ACUEDUCTOS', 'CONSTRUCCIÓN DE ALCANTARILLADOS Y ACUEDUCTOS'), ('INFRAESTRUCTURA ELÉCTRICA', 'INFRAESTRUCTURA ELÉCTRICA'), ('SUMINISTRO', 'SUMINISTRO')], max_length=1000, verbose_name='Tipo de obra'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_ejecutado',
            field=models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Valor ejecutado'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_en_sm',
            field=models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Valor en SM segun participación'),
        ),
    ]
