# Generated by Django 2.0.5 on 2018-07-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0009_auto_20180722_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valorsm',
            name='valor',
            field=models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Valor salario mínimo'),
        ),
    ]
