# Generated by Django 2.0.5 on 2018-07-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0010_auto_20180722_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='valor_ejecutado',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Valor ejecutado'),
        ),
    ]
