# Generated by Django 2.0.5 on 2018-07-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0011_auto_20180722_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='valor_en_sm',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Valor en SM segun participación'),
        ),
    ]
