# Generated by Django 2.2.4 on 2021-01-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0012_auto_20180722_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='empresa',
            field=models.CharField(choices=[('NDAM', 'NDAM'), ('ARMELCO SAS', 'ARMELCO SAS')], default='NDAM', max_length=15, verbose_name='empresa'),
        ),
    ]
